#!/bin/bash

# Append note if formatting was applied
if [ -f .git/.gofmt-flag ]; then
    echo "" >> "$1"
    echo "[auto] go fmt applied to staged Go files" >> "$1"
    rm .git/.gofmt-flag
fi

if [ -f .git/.prettier-flag ]; then
    echo "" >> "$1"
    echo "[auto] prettier applied to JavaScript, CSS, and HTML files" >> "$1"
    rm .git/.prettier-flag
fi
