#!/bin/bash

# Only append note if gofmt or prettier flag is present
if [ -f .git/.gofmt-flag ]; then
    echo "" >> "$1"
    echo "[auto] go fmt applied to staged files" >> "$1"
    rm .git/.gofmt-flag
fi

if [ -f .git/.prettier-flag ]; then
    echo "" >> "$1"
    echo "[auto] prettier applied to template/index.template" >> "$1"
    rm .git/.prettier-flag
fi
